# Generated by Django 2.1.5 on 2019-02-13 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190213_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 13, 13, 52, 34, 519501, tzinfo=utc)),
        ),
    ]
