# Generated by Django 2.1.5 on 2019-02-16 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190214_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 10, 35, 51, 900703, tzinfo=utc)),
        ),
    ]
