# Generated by Django 2.1.5 on 2019-02-16 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190216_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 10, 38, 9, 768611, tzinfo=utc)),
        ),
    ]
